# Generated by Django 4.1.5 on 2023-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
    ]
