# Generated by Django 4.1.5 on 2023-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_alter_student_backlog_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0'),
        ),
    ]
