# Generated by Django 4.1.5 on 2023-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0004_alter_student_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
