# Generated by Django 4.1.5 on 2023-02-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0005_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_year_percentage',
            new_name='current_cgpa',
        ),
    ]
