# Generated by Django 4.1.5 on 2023-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_rename_current_year_percentage_student_current_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
