# Generated by Django 4.1.5 on 2023-02-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0008_alter_student_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backlog',
            field=models.CharField(max_length=20),
        ),
    ]
