# Generated by Django 4.1.5 on 2023-02-12 03:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0016_alter_student_phone_alter_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
