# Generated by Django 4.1.7 on 2023-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0019_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
