# Generated by Django 4.1.7 on 2023-03-04 05:14

import a1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0020_alter_student_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13, validators=[a1.models.validate_mobile_number]),
        ),
    ]
