# Generated by Django 4.1.7 on 2023-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0022_alter_student_current_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
