# Generated by Django 4.1.7 on 2023-03-04 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0024_alter_student_current_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
