# Generated by Django 4.1.7 on 2023-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0025_alter_student_current_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.CharField(max_length=5),
        ),
    ]
